# Generated by Django 6.0.3 on 2026-05-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juices', '0006_notification_user_reward_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
