# Generated by Django 6.0.3 on 2026-05-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juices', '0008_customuser_device_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
